samples = [{"labels": ["HTTP"], "payload": "GET"}, {"labels": ["HTTP"], "payload": "PUT"},
           {"labels": ["HTTP"], "payload": "POST"}, {"labels": ["HTTP"], "payload": "DELETE"},
           {"labels": ["NTP"], "payload": "NTP"}, {"labels": ["PHP"], "payload": "GET /admin.php HTTP/1.1\n\n"},
           {"labels": ["WordPress"], "payload": "GET /wpadmin HTTP/1.1\n\n"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /myapp?q=mike'or1=1;"},
           {"labels": ["SMTP"], "payload": "ELHO"}, {"labels": ["BOT"], "payload": "aksjdfaskjdfasdf"},
           {"labels": ["BOT"], "payload": "asdfkjsa9df8sakdjfas"},
           {"labels": ["BOT"], "payload": "3rfdsfiuiuhqejnrk;kjrnfewe"},
           {"labels": ["BOT"], "payload": "EpuNFNLixprceEXFwxtZ"},
           {"labels": ["HTTP"], "payload": "GET /EpuNFNLixprceEXFwxtZ"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /EpuNFNLixprceEXFwxtZ.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /EpuNFNLixprceEXFwxtZ.php/?user=EpuNFNLixprceEXFwxtZ'or EpuNFNLixprceEXFwxtZ=EpuNFNLixprceEXFwxtZ"},
           {"labels": ["BOT"], "payload": "HAiFJliLVEkfcJEGoETi"},
           {"labels": ["HTTP"], "payload": "GET /HAiFJliLVEkfcJEGoETi"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /HAiFJliLVEkfcJEGoETi.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /HAiFJliLVEkfcJEGoETi.php/?user=HAiFJliLVEkfcJEGoETi'or HAiFJliLVEkfcJEGoETi=HAiFJliLVEkfcJEGoETi"},
           {"labels": ["BOT"], "payload": "CoSiomUbMbnIEPuXElol"},
           {"labels": ["HTTP"], "payload": "GET /CoSiomUbMbnIEPuXElol"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /CoSiomUbMbnIEPuXElol.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /CoSiomUbMbnIEPuXElol.php/?user=CoSiomUbMbnIEPuXElol'or CoSiomUbMbnIEPuXElol=CoSiomUbMbnIEPuXElol"},
           {"labels": ["BOT"], "payload": "WifwBJJdEZxqrFsMGpTW"},
           {"labels": ["HTTP"], "payload": "GET /WifwBJJdEZxqrFsMGpTW"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /WifwBJJdEZxqrFsMGpTW.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /WifwBJJdEZxqrFsMGpTW.php/?user=WifwBJJdEZxqrFsMGpTW'or WifwBJJdEZxqrFsMGpTW=WifwBJJdEZxqrFsMGpTW"},
           {"labels": ["BOT"], "payload": "qabahKnEhwTmNYsJJBqK"},
           {"labels": ["HTTP"], "payload": "GET /qabahKnEhwTmNYsJJBqK"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /qabahKnEhwTmNYsJJBqK.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /qabahKnEhwTmNYsJJBqK.php/?user=qabahKnEhwTmNYsJJBqK'or qabahKnEhwTmNYsJJBqK=qabahKnEhwTmNYsJJBqK"},
           {"labels": ["BOT"], "payload": "msmJOsyYlmZqGqKfknAF"},
           {"labels": ["HTTP"], "payload": "GET /msmJOsyYlmZqGqKfknAF"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /msmJOsyYlmZqGqKfknAF.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /msmJOsyYlmZqGqKfknAF.php/?user=msmJOsyYlmZqGqKfknAF'or msmJOsyYlmZqGqKfknAF=msmJOsyYlmZqGqKfknAF"},
           {"labels": ["BOT"], "payload": "eLMAjSZovdBtNFBIdJgg"},
           {"labels": ["HTTP"], "payload": "GET /eLMAjSZovdBtNFBIdJgg"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /eLMAjSZovdBtNFBIdJgg.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /eLMAjSZovdBtNFBIdJgg.php/?user=eLMAjSZovdBtNFBIdJgg'or eLMAjSZovdBtNFBIdJgg=eLMAjSZovdBtNFBIdJgg"},
           {"labels": ["BOT"], "payload": "ZfzIDYZhDFmsJfpuRtQD"},
           {"labels": ["HTTP"], "payload": "GET /ZfzIDYZhDFmsJfpuRtQD"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /ZfzIDYZhDFmsJfpuRtQD.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /ZfzIDYZhDFmsJfpuRtQD.php/?user=ZfzIDYZhDFmsJfpuRtQD'or ZfzIDYZhDFmsJfpuRtQD=ZfzIDYZhDFmsJfpuRtQD"},
           {"labels": ["BOT"], "payload": "BEytqUHWGAjGCIwnyvJK"},
           {"labels": ["HTTP"], "payload": "GET /BEytqUHWGAjGCIwnyvJK"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /BEytqUHWGAjGCIwnyvJK.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /BEytqUHWGAjGCIwnyvJK.php/?user=BEytqUHWGAjGCIwnyvJK'or BEytqUHWGAjGCIwnyvJK=BEytqUHWGAjGCIwnyvJK"},
           {"labels": ["BOT"], "payload": "QrhyyWVWYmMlyCRJPCpv"},
           {"labels": ["HTTP"], "payload": "GET /QrhyyWVWYmMlyCRJPCpv"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /QrhyyWVWYmMlyCRJPCpv.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /QrhyyWVWYmMlyCRJPCpv.php/?user=QrhyyWVWYmMlyCRJPCpv'or QrhyyWVWYmMlyCRJPCpv=QrhyyWVWYmMlyCRJPCpv"},
           {"labels": ["BOT"], "payload": "pRoGFSIyoymwBlrzeMei"},
           {"labels": ["HTTP"], "payload": "GET /pRoGFSIyoymwBlrzeMei"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /pRoGFSIyoymwBlrzeMei.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /pRoGFSIyoymwBlrzeMei.php/?user=pRoGFSIyoymwBlrzeMei'or pRoGFSIyoymwBlrzeMei=pRoGFSIyoymwBlrzeMei"},
           {"labels": ["BOT"], "payload": "TUkPDFIjGuckYnQGpHXv"},
           {"labels": ["HTTP"], "payload": "GET /TUkPDFIjGuckYnQGpHXv"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /TUkPDFIjGuckYnQGpHXv.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /TUkPDFIjGuckYnQGpHXv.php/?user=TUkPDFIjGuckYnQGpHXv'or TUkPDFIjGuckYnQGpHXv=TUkPDFIjGuckYnQGpHXv"},
           {"labels": ["BOT"], "payload": "pXtFhPMANBYAtDpcOefk"},
           {"labels": ["HTTP"], "payload": "GET /pXtFhPMANBYAtDpcOefk"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /pXtFhPMANBYAtDpcOefk.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /pXtFhPMANBYAtDpcOefk.php/?user=pXtFhPMANBYAtDpcOefk'or pXtFhPMANBYAtDpcOefk=pXtFhPMANBYAtDpcOefk"},
           {"labels": ["BOT"], "payload": "fxAvJxfnAfamIjGHMnnJ"},
           {"labels": ["HTTP"], "payload": "GET /fxAvJxfnAfamIjGHMnnJ"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /fxAvJxfnAfamIjGHMnnJ.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /fxAvJxfnAfamIjGHMnnJ.php/?user=fxAvJxfnAfamIjGHMnnJ'or fxAvJxfnAfamIjGHMnnJ=fxAvJxfnAfamIjGHMnnJ"},
           {"labels": ["BOT"], "payload": "aQoaJtidgHJzVgeBEqAK"},
           {"labels": ["HTTP"], "payload": "GET /aQoaJtidgHJzVgeBEqAK"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /aQoaJtidgHJzVgeBEqAK.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /aQoaJtidgHJzVgeBEqAK.php/?user=aQoaJtidgHJzVgeBEqAK'or aQoaJtidgHJzVgeBEqAK=aQoaJtidgHJzVgeBEqAK"},
           {"labels": ["BOT"], "payload": "wQfxLunGYAjlmoolvhQv"},
           {"labels": ["HTTP"], "payload": "GET /wQfxLunGYAjlmoolvhQv"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /wQfxLunGYAjlmoolvhQv.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /wQfxLunGYAjlmoolvhQv.php/?user=wQfxLunGYAjlmoolvhQv'or wQfxLunGYAjlmoolvhQv=wQfxLunGYAjlmoolvhQv"},
           {"labels": ["BOT"], "payload": "BtgcSsZBhvUBimimRqKG"},
           {"labels": ["HTTP"], "payload": "GET /BtgcSsZBhvUBimimRqKG"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /BtgcSsZBhvUBimimRqKG.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /BtgcSsZBhvUBimimRqKG.php/?user=BtgcSsZBhvUBimimRqKG'or BtgcSsZBhvUBimimRqKG=BtgcSsZBhvUBimimRqKG"},
           {"labels": ["BOT"], "payload": "onwjcgBbjAYmmEDOuXAR"},
           {"labels": ["HTTP"], "payload": "GET /onwjcgBbjAYmmEDOuXAR"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /onwjcgBbjAYmmEDOuXAR.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /onwjcgBbjAYmmEDOuXAR.php/?user=onwjcgBbjAYmmEDOuXAR'or onwjcgBbjAYmmEDOuXAR=onwjcgBbjAYmmEDOuXAR"},
           {"labels": ["BOT"], "payload": "yFWoXKwzMdjYgpKOSpRX"},
           {"labels": ["HTTP"], "payload": "GET /yFWoXKwzMdjYgpKOSpRX"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /yFWoXKwzMdjYgpKOSpRX.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /yFWoXKwzMdjYgpKOSpRX.php/?user=yFWoXKwzMdjYgpKOSpRX'or yFWoXKwzMdjYgpKOSpRX=yFWoXKwzMdjYgpKOSpRX"},
           {"labels": ["BOT"], "payload": "BeWKkjAaVeaztEvYLgQh"},
           {"labels": ["HTTP"], "payload": "GET /BeWKkjAaVeaztEvYLgQh"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /BeWKkjAaVeaztEvYLgQh.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /BeWKkjAaVeaztEvYLgQh.php/?user=BeWKkjAaVeaztEvYLgQh'or BeWKkjAaVeaztEvYLgQh=BeWKkjAaVeaztEvYLgQh"},
           {"labels": ["BOT"], "payload": "vttZuTuScZBZIhobIuXy"},
           {"labels": ["HTTP"], "payload": "GET /vttZuTuScZBZIhobIuXy"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /vttZuTuScZBZIhobIuXy.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /vttZuTuScZBZIhobIuXy.php/?user=vttZuTuScZBZIhobIuXy'or vttZuTuScZBZIhobIuXy=vttZuTuScZBZIhobIuXy"},
           {"labels": ["BOT"], "payload": "dWhmjKlsYeCSbEBIfouB"},
           {"labels": ["HTTP"], "payload": "GET /dWhmjKlsYeCSbEBIfouB"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /dWhmjKlsYeCSbEBIfouB.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /dWhmjKlsYeCSbEBIfouB.php/?user=dWhmjKlsYeCSbEBIfouB'or dWhmjKlsYeCSbEBIfouB=dWhmjKlsYeCSbEBIfouB"},
           {"labels": ["BOT"], "payload": "NysQysUaTvapIYcVudPG"},
           {"labels": ["HTTP"], "payload": "GET /NysQysUaTvapIYcVudPG"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /NysQysUaTvapIYcVudPG.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /NysQysUaTvapIYcVudPG.php/?user=NysQysUaTvapIYcVudPG'or NysQysUaTvapIYcVudPG=NysQysUaTvapIYcVudPG"},
           {"labels": ["BOT"], "payload": "QzURICIVpCuaZpEWtCqS"},
           {"labels": ["HTTP"], "payload": "GET /QzURICIVpCuaZpEWtCqS"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /QzURICIVpCuaZpEWtCqS.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /QzURICIVpCuaZpEWtCqS.php/?user=QzURICIVpCuaZpEWtCqS'or QzURICIVpCuaZpEWtCqS=QzURICIVpCuaZpEWtCqS"},
           {"labels": ["BOT"], "payload": "EKTQroVHxUxykgnYkOKv"},
           {"labels": ["HTTP"], "payload": "GET /EKTQroVHxUxykgnYkOKv"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /EKTQroVHxUxykgnYkOKv.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /EKTQroVHxUxykgnYkOKv.php/?user=EKTQroVHxUxykgnYkOKv'or EKTQroVHxUxykgnYkOKv=EKTQroVHxUxykgnYkOKv"},
           {"labels": ["BOT"], "payload": "NFSILtGAkgNIgFHoxJgC"},
           {"labels": ["HTTP"], "payload": "GET /NFSILtGAkgNIgFHoxJgC"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /NFSILtGAkgNIgFHoxJgC.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /NFSILtGAkgNIgFHoxJgC.php/?user=NFSILtGAkgNIgFHoxJgC'or NFSILtGAkgNIgFHoxJgC=NFSILtGAkgNIgFHoxJgC"},
           {"labels": ["BOT"], "payload": "lrunPyPAwDOrwaUhwecX"},
           {"labels": ["HTTP"], "payload": "GET /lrunPyPAwDOrwaUhwecX"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /lrunPyPAwDOrwaUhwecX.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /lrunPyPAwDOrwaUhwecX.php/?user=lrunPyPAwDOrwaUhwecX'or lrunPyPAwDOrwaUhwecX=lrunPyPAwDOrwaUhwecX"},
           {"labels": ["BOT"], "payload": "XPUHevqZyFutqjUKUHeT"},
           {"labels": ["HTTP"], "payload": "GET /XPUHevqZyFutqjUKUHeT"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /XPUHevqZyFutqjUKUHeT.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /XPUHevqZyFutqjUKUHeT.php/?user=XPUHevqZyFutqjUKUHeT'or XPUHevqZyFutqjUKUHeT=XPUHevqZyFutqjUKUHeT"},
           {"labels": ["BOT"], "payload": "JCYRzdfTEMCJNQetrqPp"},
           {"labels": ["HTTP"], "payload": "GET /JCYRzdfTEMCJNQetrqPp"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /JCYRzdfTEMCJNQetrqPp.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /JCYRzdfTEMCJNQetrqPp.php/?user=JCYRzdfTEMCJNQetrqPp'or JCYRzdfTEMCJNQetrqPp=JCYRzdfTEMCJNQetrqPp"},
           {"labels": ["BOT"], "payload": "BabBLcLCGyuWIVohXYTt"},
           {"labels": ["HTTP"], "payload": "GET /BabBLcLCGyuWIVohXYTt"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /BabBLcLCGyuWIVohXYTt.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /BabBLcLCGyuWIVohXYTt.php/?user=BabBLcLCGyuWIVohXYTt'or BabBLcLCGyuWIVohXYTt=BabBLcLCGyuWIVohXYTt"},
           {"labels": ["BOT"], "payload": "pVJNfNbhFMAXQCTfaweh"},
           {"labels": ["HTTP"], "payload": "GET /pVJNfNbhFMAXQCTfaweh"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /pVJNfNbhFMAXQCTfaweh.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /pVJNfNbhFMAXQCTfaweh.php/?user=pVJNfNbhFMAXQCTfaweh'or pVJNfNbhFMAXQCTfaweh=pVJNfNbhFMAXQCTfaweh"},
           {"labels": ["BOT"], "payload": "dqJpqmWFhiLOBnSyuETW"},
           {"labels": ["HTTP"], "payload": "GET /dqJpqmWFhiLOBnSyuETW"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /dqJpqmWFhiLOBnSyuETW.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /dqJpqmWFhiLOBnSyuETW.php/?user=dqJpqmWFhiLOBnSyuETW'or dqJpqmWFhiLOBnSyuETW=dqJpqmWFhiLOBnSyuETW"},
           {"labels": ["BOT"], "payload": "CgbvTXGiTOVbqxcOHuJf"},
           {"labels": ["HTTP"], "payload": "GET /CgbvTXGiTOVbqxcOHuJf"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /CgbvTXGiTOVbqxcOHuJf.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /CgbvTXGiTOVbqxcOHuJf.php/?user=CgbvTXGiTOVbqxcOHuJf'or CgbvTXGiTOVbqxcOHuJf=CgbvTXGiTOVbqxcOHuJf"},
           {"labels": ["BOT"], "payload": "puOwNDNwHBkXVRZQcucK"},
           {"labels": ["HTTP"], "payload": "GET /puOwNDNwHBkXVRZQcucK"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /puOwNDNwHBkXVRZQcucK.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /puOwNDNwHBkXVRZQcucK.php/?user=puOwNDNwHBkXVRZQcucK'or puOwNDNwHBkXVRZQcucK=puOwNDNwHBkXVRZQcucK"},
           {"labels": ["BOT"], "payload": "vGfdPYeRRcarvpAyjAAt"},
           {"labels": ["HTTP"], "payload": "GET /vGfdPYeRRcarvpAyjAAt"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /vGfdPYeRRcarvpAyjAAt.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /vGfdPYeRRcarvpAyjAAt.php/?user=vGfdPYeRRcarvpAyjAAt'or vGfdPYeRRcarvpAyjAAt=vGfdPYeRRcarvpAyjAAt"},
           {"labels": ["BOT"], "payload": "giirqKrMyGMzgfoKbZok"},
           {"labels": ["HTTP"], "payload": "GET /giirqKrMyGMzgfoKbZok"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /giirqKrMyGMzgfoKbZok.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /giirqKrMyGMzgfoKbZok.php/?user=giirqKrMyGMzgfoKbZok'or giirqKrMyGMzgfoKbZok=giirqKrMyGMzgfoKbZok"},
           {"labels": ["BOT"], "payload": "HUyiBycszbzWBGtfoIQr"},
           {"labels": ["HTTP"], "payload": "GET /HUyiBycszbzWBGtfoIQr"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /HUyiBycszbzWBGtfoIQr.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /HUyiBycszbzWBGtfoIQr.php/?user=HUyiBycszbzWBGtfoIQr'or HUyiBycszbzWBGtfoIQr=HUyiBycszbzWBGtfoIQr"},
           {"labels": ["BOT"], "payload": "QFgWGzPKyOroBLnvetWL"},
           {"labels": ["HTTP"], "payload": "GET /QFgWGzPKyOroBLnvetWL"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /QFgWGzPKyOroBLnvetWL.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /QFgWGzPKyOroBLnvetWL.php/?user=QFgWGzPKyOroBLnvetWL'or QFgWGzPKyOroBLnvetWL=QFgWGzPKyOroBLnvetWL"},
           {"labels": ["BOT"], "payload": "ZVbTEZonhWILHOhuYTyv"},
           {"labels": ["HTTP"], "payload": "GET /ZVbTEZonhWILHOhuYTyv"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /ZVbTEZonhWILHOhuYTyv.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /ZVbTEZonhWILHOhuYTyv.php/?user=ZVbTEZonhWILHOhuYTyv'or ZVbTEZonhWILHOhuYTyv=ZVbTEZonhWILHOhuYTyv"},
           {"labels": ["BOT"], "payload": "LuxVSwzdcPMdNYxszamQ"},
           {"labels": ["HTTP"], "payload": "GET /LuxVSwzdcPMdNYxszamQ"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /LuxVSwzdcPMdNYxszamQ.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /LuxVSwzdcPMdNYxszamQ.php/?user=LuxVSwzdcPMdNYxszamQ'or LuxVSwzdcPMdNYxszamQ=LuxVSwzdcPMdNYxszamQ"},
           {"labels": ["BOT"], "payload": "TrcendVrOuantKZaKAkN"},
           {"labels": ["HTTP"], "payload": "GET /TrcendVrOuantKZaKAkN"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /TrcendVrOuantKZaKAkN.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /TrcendVrOuantKZaKAkN.php/?user=TrcendVrOuantKZaKAkN'or TrcendVrOuantKZaKAkN=TrcendVrOuantKZaKAkN"},
           {"labels": ["BOT"], "payload": "OSRXLrLbKYIUpKcRcjek"},
           {"labels": ["HTTP"], "payload": "GET /OSRXLrLbKYIUpKcRcjek"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /OSRXLrLbKYIUpKcRcjek.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /OSRXLrLbKYIUpKcRcjek.php/?user=OSRXLrLbKYIUpKcRcjek'or OSRXLrLbKYIUpKcRcjek=OSRXLrLbKYIUpKcRcjek"},
           {"labels": ["BOT"], "payload": "PgxOxiCuDpjggfIiozyk"},
           {"labels": ["HTTP"], "payload": "GET /PgxOxiCuDpjggfIiozyk"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /PgxOxiCuDpjggfIiozyk.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /PgxOxiCuDpjggfIiozyk.php/?user=PgxOxiCuDpjggfIiozyk'or PgxOxiCuDpjggfIiozyk=PgxOxiCuDpjggfIiozyk"},
           {"labels": ["BOT"], "payload": "fgooShsJRhYfGYItkvbZ"},
           {"labels": ["HTTP"], "payload": "GET /fgooShsJRhYfGYItkvbZ"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /fgooShsJRhYfGYItkvbZ.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /fgooShsJRhYfGYItkvbZ.php/?user=fgooShsJRhYfGYItkvbZ'or fgooShsJRhYfGYItkvbZ=fgooShsJRhYfGYItkvbZ"},
           {"labels": ["BOT"], "payload": "XiceEyImrfBNwQbWNOzl"},
           {"labels": ["HTTP"], "payload": "GET /XiceEyImrfBNwQbWNOzl"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /XiceEyImrfBNwQbWNOzl.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /XiceEyImrfBNwQbWNOzl.php/?user=XiceEyImrfBNwQbWNOzl'or XiceEyImrfBNwQbWNOzl=XiceEyImrfBNwQbWNOzl"},
           {"labels": ["BOT"], "payload": "qkxUVxMIDlXaBFKCotYH"},
           {"labels": ["HTTP"], "payload": "GET /qkxUVxMIDlXaBFKCotYH"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /qkxUVxMIDlXaBFKCotYH.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /qkxUVxMIDlXaBFKCotYH.php/?user=qkxUVxMIDlXaBFKCotYH'or qkxUVxMIDlXaBFKCotYH=qkxUVxMIDlXaBFKCotYH"},
           {"labels": ["BOT"], "payload": "HfzVeMGsoVRliEtUhJdB"},
           {"labels": ["HTTP"], "payload": "GET /HfzVeMGsoVRliEtUhJdB"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /HfzVeMGsoVRliEtUhJdB.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /HfzVeMGsoVRliEtUhJdB.php/?user=HfzVeMGsoVRliEtUhJdB'or HfzVeMGsoVRliEtUhJdB=HfzVeMGsoVRliEtUhJdB"},
           {"labels": ["BOT"], "payload": "NuiWKKmYGQodWVHOUHwA"},
           {"labels": ["HTTP"], "payload": "GET /NuiWKKmYGQodWVHOUHwA"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /NuiWKKmYGQodWVHOUHwA.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /NuiWKKmYGQodWVHOUHwA.php/?user=NuiWKKmYGQodWVHOUHwA'or NuiWKKmYGQodWVHOUHwA=NuiWKKmYGQodWVHOUHwA"},
           {"labels": ["BOT"], "payload": "xFXqizxiPwclyOzYWwWF"},
           {"labels": ["HTTP"], "payload": "GET /xFXqizxiPwclyOzYWwWF"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /xFXqizxiPwclyOzYWwWF.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /xFXqizxiPwclyOzYWwWF.php/?user=xFXqizxiPwclyOzYWwWF'or xFXqizxiPwclyOzYWwWF=xFXqizxiPwclyOzYWwWF"},
           {"labels": ["BOT"], "payload": "xfEhZeGZzUfUPLRiCkEo"},
           {"labels": ["HTTP"], "payload": "GET /xfEhZeGZzUfUPLRiCkEo"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /xfEhZeGZzUfUPLRiCkEo.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /xfEhZeGZzUfUPLRiCkEo.php/?user=xfEhZeGZzUfUPLRiCkEo'or xfEhZeGZzUfUPLRiCkEo=xfEhZeGZzUfUPLRiCkEo"},
           {"labels": ["BOT"], "payload": "PXRPfxoSRxnkAYWmWunY"},
           {"labels": ["HTTP"], "payload": "GET /PXRPfxoSRxnkAYWmWunY"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /PXRPfxoSRxnkAYWmWunY.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /PXRPfxoSRxnkAYWmWunY.php/?user=PXRPfxoSRxnkAYWmWunY'or PXRPfxoSRxnkAYWmWunY=PXRPfxoSRxnkAYWmWunY"},
           {"labels": ["BOT"], "payload": "PmuDCkWMeOBvXQeACDqI"},
           {"labels": ["HTTP"], "payload": "GET /PmuDCkWMeOBvXQeACDqI"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /PmuDCkWMeOBvXQeACDqI.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /PmuDCkWMeOBvXQeACDqI.php/?user=PmuDCkWMeOBvXQeACDqI'or PmuDCkWMeOBvXQeACDqI=PmuDCkWMeOBvXQeACDqI"},
           {"labels": ["BOT"], "payload": "lHEbGYgYTEceQxwnHklt"},
           {"labels": ["HTTP"], "payload": "GET /lHEbGYgYTEceQxwnHklt"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /lHEbGYgYTEceQxwnHklt.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /lHEbGYgYTEceQxwnHklt.php/?user=lHEbGYgYTEceQxwnHklt'or lHEbGYgYTEceQxwnHklt=lHEbGYgYTEceQxwnHklt"},
           {"labels": ["BOT"], "payload": "PrWaaUmdpXjFDyixhCJr"},
           {"labels": ["HTTP"], "payload": "GET /PrWaaUmdpXjFDyixhCJr"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /PrWaaUmdpXjFDyixhCJr.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /PrWaaUmdpXjFDyixhCJr.php/?user=PrWaaUmdpXjFDyixhCJr'or PrWaaUmdpXjFDyixhCJr=PrWaaUmdpXjFDyixhCJr"},
           {"labels": ["BOT"], "payload": "jkFsnSSDgyaXzXsXKPNR"},
           {"labels": ["HTTP"], "payload": "GET /jkFsnSSDgyaXzXsXKPNR"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /jkFsnSSDgyaXzXsXKPNR.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /jkFsnSSDgyaXzXsXKPNR.php/?user=jkFsnSSDgyaXzXsXKPNR'or jkFsnSSDgyaXzXsXKPNR=jkFsnSSDgyaXzXsXKPNR"},
           {"labels": ["BOT"], "payload": "oyRTEfjDhZDUAKjZjebT"},
           {"labels": ["HTTP"], "payload": "GET /oyRTEfjDhZDUAKjZjebT"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /oyRTEfjDhZDUAKjZjebT.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /oyRTEfjDhZDUAKjZjebT.php/?user=oyRTEfjDhZDUAKjZjebT'or oyRTEfjDhZDUAKjZjebT=oyRTEfjDhZDUAKjZjebT"},
           {"labels": ["BOT"], "payload": "hYrnHroDaPMJlGSYgzhw"},
           {"labels": ["HTTP"], "payload": "GET /hYrnHroDaPMJlGSYgzhw"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /hYrnHroDaPMJlGSYgzhw.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /hYrnHroDaPMJlGSYgzhw.php/?user=hYrnHroDaPMJlGSYgzhw'or hYrnHroDaPMJlGSYgzhw=hYrnHroDaPMJlGSYgzhw"},
           {"labels": ["BOT"], "payload": "JRdVcvRzPCadJrvdVqrd"},
           {"labels": ["HTTP"], "payload": "GET /JRdVcvRzPCadJrvdVqrd"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /JRdVcvRzPCadJrvdVqrd.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /JRdVcvRzPCadJrvdVqrd.php/?user=JRdVcvRzPCadJrvdVqrd'or JRdVcvRzPCadJrvdVqrd=JRdVcvRzPCadJrvdVqrd"},
           {"labels": ["BOT"], "payload": "UpHEFYZvIhFhrlNpxwZA"},
           {"labels": ["HTTP"], "payload": "GET /UpHEFYZvIhFhrlNpxwZA"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /UpHEFYZvIhFhrlNpxwZA.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /UpHEFYZvIhFhrlNpxwZA.php/?user=UpHEFYZvIhFhrlNpxwZA'or UpHEFYZvIhFhrlNpxwZA=UpHEFYZvIhFhrlNpxwZA"},
           {"labels": ["BOT"], "payload": "lvQqhBjzXhfYRqYbFzwE"},
           {"labels": ["HTTP"], "payload": "GET /lvQqhBjzXhfYRqYbFzwE"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /lvQqhBjzXhfYRqYbFzwE.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /lvQqhBjzXhfYRqYbFzwE.php/?user=lvQqhBjzXhfYRqYbFzwE'or lvQqhBjzXhfYRqYbFzwE=lvQqhBjzXhfYRqYbFzwE"},
           {"labels": ["BOT"], "payload": "zFsiwxdCTmvDigUFkcMi"},
           {"labels": ["HTTP"], "payload": "GET /zFsiwxdCTmvDigUFkcMi"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /zFsiwxdCTmvDigUFkcMi.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /zFsiwxdCTmvDigUFkcMi.php/?user=zFsiwxdCTmvDigUFkcMi'or zFsiwxdCTmvDigUFkcMi=zFsiwxdCTmvDigUFkcMi"},
           {"labels": ["BOT"], "payload": "qNXnCxepbDKAAnwhnVoh"},
           {"labels": ["HTTP"], "payload": "GET /qNXnCxepbDKAAnwhnVoh"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /qNXnCxepbDKAAnwhnVoh.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /qNXnCxepbDKAAnwhnVoh.php/?user=qNXnCxepbDKAAnwhnVoh'or qNXnCxepbDKAAnwhnVoh=qNXnCxepbDKAAnwhnVoh"},
           {"labels": ["BOT"], "payload": "bVpwqinZWnCTweSnSsIV"},
           {"labels": ["HTTP"], "payload": "GET /bVpwqinZWnCTweSnSsIV"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /bVpwqinZWnCTweSnSsIV.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /bVpwqinZWnCTweSnSsIV.php/?user=bVpwqinZWnCTweSnSsIV'or bVpwqinZWnCTweSnSsIV=bVpwqinZWnCTweSnSsIV"},
           {"labels": ["BOT"], "payload": "GcWfHPAnVFTkdeGvFbkM"},
           {"labels": ["HTTP"], "payload": "GET /GcWfHPAnVFTkdeGvFbkM"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /GcWfHPAnVFTkdeGvFbkM.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /GcWfHPAnVFTkdeGvFbkM.php/?user=GcWfHPAnVFTkdeGvFbkM'or GcWfHPAnVFTkdeGvFbkM=GcWfHPAnVFTkdeGvFbkM"},
           {"labels": ["BOT"], "payload": "LuWYOMxovpMYqtnOFFVN"},
           {"labels": ["HTTP"], "payload": "GET /LuWYOMxovpMYqtnOFFVN"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /LuWYOMxovpMYqtnOFFVN.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /LuWYOMxovpMYqtnOFFVN.php/?user=LuWYOMxovpMYqtnOFFVN'or LuWYOMxovpMYqtnOFFVN=LuWYOMxovpMYqtnOFFVN"},
           {"labels": ["BOT"], "payload": "VUJdLuspIqoKjUjhzzMn"},
           {"labels": ["HTTP"], "payload": "GET /VUJdLuspIqoKjUjhzzMn"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /VUJdLuspIqoKjUjhzzMn.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /VUJdLuspIqoKjUjhzzMn.php/?user=VUJdLuspIqoKjUjhzzMn'or VUJdLuspIqoKjUjhzzMn=VUJdLuspIqoKjUjhzzMn"},
           {"labels": ["BOT"], "payload": "qVwOxdOrPcIGtqkKpCnt"},
           {"labels": ["HTTP"], "payload": "GET /qVwOxdOrPcIGtqkKpCnt"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /qVwOxdOrPcIGtqkKpCnt.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /qVwOxdOrPcIGtqkKpCnt.php/?user=qVwOxdOrPcIGtqkKpCnt'or qVwOxdOrPcIGtqkKpCnt=qVwOxdOrPcIGtqkKpCnt"},
           {"labels": ["BOT"], "payload": "AoDxwQubkeRbIfPBOgiP"},
           {"labels": ["HTTP"], "payload": "GET /AoDxwQubkeRbIfPBOgiP"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /AoDxwQubkeRbIfPBOgiP.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /AoDxwQubkeRbIfPBOgiP.php/?user=AoDxwQubkeRbIfPBOgiP'or AoDxwQubkeRbIfPBOgiP=AoDxwQubkeRbIfPBOgiP"},
           {"labels": ["BOT"], "payload": "tQLOyzsrTcbntCrVufxd"},
           {"labels": ["HTTP"], "payload": "GET /tQLOyzsrTcbntCrVufxd"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /tQLOyzsrTcbntCrVufxd.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /tQLOyzsrTcbntCrVufxd.php/?user=tQLOyzsrTcbntCrVufxd'or tQLOyzsrTcbntCrVufxd=tQLOyzsrTcbntCrVufxd"},
           {"labels": ["BOT"], "payload": "FcOBkDijzdFwUgXDqKnx"},
           {"labels": ["HTTP"], "payload": "GET /FcOBkDijzdFwUgXDqKnx"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /FcOBkDijzdFwUgXDqKnx.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /FcOBkDijzdFwUgXDqKnx.php/?user=FcOBkDijzdFwUgXDqKnx'or FcOBkDijzdFwUgXDqKnx=FcOBkDijzdFwUgXDqKnx"},
           {"labels": ["BOT"], "payload": "lUWSxicAgxEjwnpZlBVy"},
           {"labels": ["HTTP"], "payload": "GET /lUWSxicAgxEjwnpZlBVy"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /lUWSxicAgxEjwnpZlBVy.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /lUWSxicAgxEjwnpZlBVy.php/?user=lUWSxicAgxEjwnpZlBVy'or lUWSxicAgxEjwnpZlBVy=lUWSxicAgxEjwnpZlBVy"},
           {"labels": ["BOT"], "payload": "RSNaRzdpVZJlvfHnZaFW"},
           {"labels": ["HTTP"], "payload": "GET /RSNaRzdpVZJlvfHnZaFW"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /RSNaRzdpVZJlvfHnZaFW.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /RSNaRzdpVZJlvfHnZaFW.php/?user=RSNaRzdpVZJlvfHnZaFW'or RSNaRzdpVZJlvfHnZaFW=RSNaRzdpVZJlvfHnZaFW"},
           {"labels": ["BOT"], "payload": "hnzErRYBuMJZbRueQYUd"},
           {"labels": ["HTTP"], "payload": "GET /hnzErRYBuMJZbRueQYUd"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /hnzErRYBuMJZbRueQYUd.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /hnzErRYBuMJZbRueQYUd.php/?user=hnzErRYBuMJZbRueQYUd'or hnzErRYBuMJZbRueQYUd=hnzErRYBuMJZbRueQYUd"},
           {"labels": ["BOT"], "payload": "WJLfCzNkFQpFdkyoFmyd"},
           {"labels": ["HTTP"], "payload": "GET /WJLfCzNkFQpFdkyoFmyd"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /WJLfCzNkFQpFdkyoFmyd.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /WJLfCzNkFQpFdkyoFmyd.php/?user=WJLfCzNkFQpFdkyoFmyd'or WJLfCzNkFQpFdkyoFmyd=WJLfCzNkFQpFdkyoFmyd"},
           {"labels": ["BOT"], "payload": "EQcisIqVsjzoaCdXFbeU"},
           {"labels": ["HTTP"], "payload": "GET /EQcisIqVsjzoaCdXFbeU"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /EQcisIqVsjzoaCdXFbeU.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /EQcisIqVsjzoaCdXFbeU.php/?user=EQcisIqVsjzoaCdXFbeU'or EQcisIqVsjzoaCdXFbeU=EQcisIqVsjzoaCdXFbeU"},
           {"labels": ["BOT"], "payload": "BiADnIKQsenCMygwIUIu"},
           {"labels": ["HTTP"], "payload": "GET /BiADnIKQsenCMygwIUIu"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /BiADnIKQsenCMygwIUIu.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /BiADnIKQsenCMygwIUIu.php/?user=BiADnIKQsenCMygwIUIu'or BiADnIKQsenCMygwIUIu=BiADnIKQsenCMygwIUIu"},
           {"labels": ["BOT"], "payload": "wSzjtYJjCgvgutxpLEjC"},
           {"labels": ["HTTP"], "payload": "GET /wSzjtYJjCgvgutxpLEjC"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /wSzjtYJjCgvgutxpLEjC.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /wSzjtYJjCgvgutxpLEjC.php/?user=wSzjtYJjCgvgutxpLEjC'or wSzjtYJjCgvgutxpLEjC=wSzjtYJjCgvgutxpLEjC"},
           {"labels": ["BOT"], "payload": "PVqPctYIrHAGhWnFTkUh"},
           {"labels": ["HTTP"], "payload": "GET /PVqPctYIrHAGhWnFTkUh"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /PVqPctYIrHAGhWnFTkUh.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /PVqPctYIrHAGhWnFTkUh.php/?user=PVqPctYIrHAGhWnFTkUh'or PVqPctYIrHAGhWnFTkUh=PVqPctYIrHAGhWnFTkUh"},
           {"labels": ["BOT"], "payload": "wxuiTLVDUZvETFALcNPM"},
           {"labels": ["HTTP"], "payload": "GET /wxuiTLVDUZvETFALcNPM"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /wxuiTLVDUZvETFALcNPM.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /wxuiTLVDUZvETFALcNPM.php/?user=wxuiTLVDUZvETFALcNPM'or wxuiTLVDUZvETFALcNPM=wxuiTLVDUZvETFALcNPM"},
           {"labels": ["BOT"], "payload": "admBsFcnAdPkKtXRPwgE"},
           {"labels": ["HTTP"], "payload": "GET /admBsFcnAdPkKtXRPwgE"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /admBsFcnAdPkKtXRPwgE.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /admBsFcnAdPkKtXRPwgE.php/?user=admBsFcnAdPkKtXRPwgE'or admBsFcnAdPkKtXRPwgE=admBsFcnAdPkKtXRPwgE"},
           {"labels": ["BOT"], "payload": "sfDYsHZaRxsLEwOeyDfm"},
           {"labels": ["HTTP"], "payload": "GET /sfDYsHZaRxsLEwOeyDfm"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /sfDYsHZaRxsLEwOeyDfm.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /sfDYsHZaRxsLEwOeyDfm.php/?user=sfDYsHZaRxsLEwOeyDfm'or sfDYsHZaRxsLEwOeyDfm=sfDYsHZaRxsLEwOeyDfm"},
           {"labels": ["BOT"], "payload": "GYyxbgchAFjpoMULRsas"},
           {"labels": ["HTTP"], "payload": "GET /GYyxbgchAFjpoMULRsas"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /GYyxbgchAFjpoMULRsas.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /GYyxbgchAFjpoMULRsas.php/?user=GYyxbgchAFjpoMULRsas'or GYyxbgchAFjpoMULRsas=GYyxbgchAFjpoMULRsas"},
           {"labels": ["BOT"], "payload": "ixhTaKyKCqMsJCLVNOtU"},
           {"labels": ["HTTP"], "payload": "GET /ixhTaKyKCqMsJCLVNOtU"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /ixhTaKyKCqMsJCLVNOtU.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /ixhTaKyKCqMsJCLVNOtU.php/?user=ixhTaKyKCqMsJCLVNOtU'or ixhTaKyKCqMsJCLVNOtU=ixhTaKyKCqMsJCLVNOtU"},
           {"labels": ["BOT"], "payload": "hKcOijCObIKlZSJnMlPI"},
           {"labels": ["HTTP"], "payload": "GET /hKcOijCObIKlZSJnMlPI"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /hKcOijCObIKlZSJnMlPI.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /hKcOijCObIKlZSJnMlPI.php/?user=hKcOijCObIKlZSJnMlPI'or hKcOijCObIKlZSJnMlPI=hKcOijCObIKlZSJnMlPI"},
           {"labels": ["BOT"], "payload": "SuVUbzVKCUsyguTtajsb"},
           {"labels": ["HTTP"], "payload": "GET /SuVUbzVKCUsyguTtajsb"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /SuVUbzVKCUsyguTtajsb.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /SuVUbzVKCUsyguTtajsb.php/?user=SuVUbzVKCUsyguTtajsb'or SuVUbzVKCUsyguTtajsb=SuVUbzVKCUsyguTtajsb"},
           {"labels": ["BOT"], "payload": "aljPiSjRZRGGDPGUVqBC"},
           {"labels": ["HTTP"], "payload": "GET /aljPiSjRZRGGDPGUVqBC"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /aljPiSjRZRGGDPGUVqBC.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /aljPiSjRZRGGDPGUVqBC.php/?user=aljPiSjRZRGGDPGUVqBC'or aljPiSjRZRGGDPGUVqBC=aljPiSjRZRGGDPGUVqBC"},
           {"labels": ["BOT"], "payload": "VnNdtEDuTifMPRgVFcxa"},
           {"labels": ["HTTP"], "payload": "GET /VnNdtEDuTifMPRgVFcxa"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /VnNdtEDuTifMPRgVFcxa.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /VnNdtEDuTifMPRgVFcxa.php/?user=VnNdtEDuTifMPRgVFcxa'or VnNdtEDuTifMPRgVFcxa=VnNdtEDuTifMPRgVFcxa"},
           {"labels": ["BOT"], "payload": "fAyHlZGbkFBxaciNdIOd"},
           {"labels": ["HTTP"], "payload": "GET /fAyHlZGbkFBxaciNdIOd"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /fAyHlZGbkFBxaciNdIOd.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /fAyHlZGbkFBxaciNdIOd.php/?user=fAyHlZGbkFBxaciNdIOd'or fAyHlZGbkFBxaciNdIOd=fAyHlZGbkFBxaciNdIOd"},
           {"labels": ["BOT"], "payload": "ibTXlYDDghLWWRsxhYTU"},
           {"labels": ["HTTP"], "payload": "GET /ibTXlYDDghLWWRsxhYTU"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /ibTXlYDDghLWWRsxhYTU.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /ibTXlYDDghLWWRsxhYTU.php/?user=ibTXlYDDghLWWRsxhYTU'or ibTXlYDDghLWWRsxhYTU=ibTXlYDDghLWWRsxhYTU"},
           {"labels": ["BOT"], "payload": "wkaLbGerqjAkWfFWMFhK"},
           {"labels": ["HTTP"], "payload": "GET /wkaLbGerqjAkWfFWMFhK"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /wkaLbGerqjAkWfFWMFhK.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /wkaLbGerqjAkWfFWMFhK.php/?user=wkaLbGerqjAkWfFWMFhK'or wkaLbGerqjAkWfFWMFhK=wkaLbGerqjAkWfFWMFhK"},
           {"labels": ["BOT"], "payload": "psBPcdhiUUuKUbstyveY"},
           {"labels": ["HTTP"], "payload": "GET /psBPcdhiUUuKUbstyveY"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /psBPcdhiUUuKUbstyveY.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /psBPcdhiUUuKUbstyveY.php/?user=psBPcdhiUUuKUbstyveY'or psBPcdhiUUuKUbstyveY=psBPcdhiUUuKUbstyveY"},
           {"labels": ["BOT"], "payload": "kJOAERCozmdCZbOzCTFU"},
           {"labels": ["HTTP"], "payload": "GET /kJOAERCozmdCZbOzCTFU"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /kJOAERCozmdCZbOzCTFU.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /kJOAERCozmdCZbOzCTFU.php/?user=kJOAERCozmdCZbOzCTFU'or kJOAERCozmdCZbOzCTFU=kJOAERCozmdCZbOzCTFU"},
           {"labels": ["BOT"], "payload": "RNeqsSEEncMLUqdMKOOz"},
           {"labels": ["HTTP"], "payload": "GET /RNeqsSEEncMLUqdMKOOz"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /RNeqsSEEncMLUqdMKOOz.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /RNeqsSEEncMLUqdMKOOz.php/?user=RNeqsSEEncMLUqdMKOOz'or RNeqsSEEncMLUqdMKOOz=RNeqsSEEncMLUqdMKOOz"},
           {"labels": ["BOT"], "payload": "PlpjgJcdheXeFuXDlLSU"},
           {"labels": ["HTTP"], "payload": "GET /PlpjgJcdheXeFuXDlLSU"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /PlpjgJcdheXeFuXDlLSU.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /PlpjgJcdheXeFuXDlLSU.php/?user=PlpjgJcdheXeFuXDlLSU'or PlpjgJcdheXeFuXDlLSU=PlpjgJcdheXeFuXDlLSU"},
           {"labels": ["BOT"], "payload": "NcNEoncxurMfUMsKwqaK"},
           {"labels": ["HTTP"], "payload": "GET /NcNEoncxurMfUMsKwqaK"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /NcNEoncxurMfUMsKwqaK.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /NcNEoncxurMfUMsKwqaK.php/?user=NcNEoncxurMfUMsKwqaK'or NcNEoncxurMfUMsKwqaK=NcNEoncxurMfUMsKwqaK"},
           {"labels": ["BOT"], "payload": "kxhYNbsAOVpISYvfrwqV"},
           {"labels": ["HTTP"], "payload": "GET /kxhYNbsAOVpISYvfrwqV"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /kxhYNbsAOVpISYvfrwqV.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /kxhYNbsAOVpISYvfrwqV.php/?user=kxhYNbsAOVpISYvfrwqV'or kxhYNbsAOVpISYvfrwqV=kxhYNbsAOVpISYvfrwqV"},
           {"labels": ["BOT"], "payload": "yOmNxxjKAhrSEqnVlqKU"},
           {"labels": ["HTTP"], "payload": "GET /yOmNxxjKAhrSEqnVlqKU"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /yOmNxxjKAhrSEqnVlqKU.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /yOmNxxjKAhrSEqnVlqKU.php/?user=yOmNxxjKAhrSEqnVlqKU'or yOmNxxjKAhrSEqnVlqKU=yOmNxxjKAhrSEqnVlqKU"},
           {"labels": ["BOT"], "payload": "UUWKyarTmddqjWJauvFO"},
           {"labels": ["HTTP"], "payload": "GET /UUWKyarTmddqjWJauvFO"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /UUWKyarTmddqjWJauvFO.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /UUWKyarTmddqjWJauvFO.php/?user=UUWKyarTmddqjWJauvFO'or UUWKyarTmddqjWJauvFO=UUWKyarTmddqjWJauvFO"},
           {"labels": ["BOT"], "payload": "nRJHgOejhKyKAeAZMXjM"},
           {"labels": ["HTTP"], "payload": "GET /nRJHgOejhKyKAeAZMXjM"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /nRJHgOejhKyKAeAZMXjM.asp/?user=mike'or 1=1;"},
           {"labels": ["SQL-INJECTION"],
            "payload": "GET /nRJHgOejhKyKAeAZMXjM.php/?user=nRJHgOejhKyKAeAZMXjM'or nRJHgOejhKyKAeAZMXjM=nRJHgOejhKyKAeAZMXjM"},
           {"labels": ["BOT"], "payload": "TMwmYuhJTHntpgfIrNZV"},
           {"labels": ["HTTP"], "payload": "GET /TMwmYuhJTHntpgfIrNZV"},
           {"labels": ["SQL-INJECTION"], "payload": "GET /TMwmYuhJTHntpgfIrNZV.asp/?user=mike'or 1=1;"}]
